### ISSUE TITLE
Audit report (yaml)

### ISSUE THREAD

**Issue by erictheswift** [bali182/oats#141]
# npm audit report
```
yaml  2.0.0-5 - 2.2.1
Severity: high
Uncaught Exception in yaml - https://github.com/advisories/GHSA-f9xv-q969-pqx4
fix available via `npm audit fix --force`
Will install @oats-ts/openapi@0.0.48, which is a breaking change
node_modules/@oats-ts/openapi-reader/node_modules/yaml
  @oats-ts/openapi-reader  >=0.0.49
  Depends on vulnerable versions of yaml
  node_modules/@oats-ts/openapi-reader
    @oats-ts/openapi  >=0.0.49
    Depends on vulnerable versions of @oats-ts/openapi-reader
    node_modules/@oats-ts/openapi
```
Btw, is project abandoned? Utilized it well for some of my products.

**Comment by bali182** [comment]
Hey Eric, sorry for not beeing very swift on these. Is this just an `npm audit˛` warning, or something is failing? If it's an audit issue, I can branch of quickly from master, fix, test and push an update. I cannot count how many times node-fetch / yaml warnings came up...

Regarding abandonment, I have a bunch of stuff on a feature branch, but I didn't work on it for a while, but never got around to finishing it. Might jump back on it during the holidays.

**Comment by bali182** [comment]
Should be good to go on v0.0.50
